# Generated by Django 4.2.6 on 2023-10-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funding',
            name='cid',
            field=models.CharField(max_length=100),
        ),
    ]
