# Generated by Django 4.2.6 on 2023-10-16 16:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('politicians', '0002_alter_funding_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='funding',
            name='cand_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
